/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylcq_ndkbspatch_Bspatch */

#ifndef _Included_com_ylcq_ndkbspatch_Bspatch
#define _Included_com_ylcq_ndkbspatch_Bspatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylcq_ndkbspatch_Bspatch
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ylcq_ndkbspatch_Bspatch_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
